function createfigure(yvector1)
%CREATEFIGURE(yvector1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 11-Oct-2020 15:37:37

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create bar
bar(yvector1,'Horizontal','on');

% Create xlabel
xlabel('Championships');

% Create title
title('NFL Teams with Most Championships','FontSize',24);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'YTick',['Packers' , 'Giants' , 'Bears' , 'Steelers' , 'Redskins']);
